### ISSUE TITLE
API Implementation

### ISSUE THREAD

**Issue by Zachdehooge** [Zachdehooge/Weather-Dashboard-Go#1]
# TODO
https://www.weather.gov/documentation/services-web-api#/

- [ ] Format JSON data on return
- [ ] Fetch Radar Station Info // radar/stations/{stationId} // coordinates | last lvl2 data received
- [ ] Fetch Active Alerts for the USA // /alerts/active // effective | expires | location | severity | event | headline | description
- [ ] Fetch Active Alerts for a State // /alerts/active/area/{area} // effective | expires | location | severity | event | headline | description
